### ISSUE TITLE
"/data/xnat/archive" data gone after `docker-compose down` - best practices?

### ISSUE THREAD

**Issue by seantma** [NrgXnat/xnat-docker-compose#13]
Hi @johnflavin @vsoch 

I appreciate your effort of creating this `docker-compose` container for XNAT1.7. I'm fairly new to both but was able to get an XNAT server up and running for within a short amount of time. 

Maybe I missed something in the README, but after uploading my test subjects DICOMs into XNAT archive, I was able to manage the files within the XNAT GUI as well as see it on the docker host with:

`docker exec -it $NAME ls -laR /data/xnat/archive`

However after after shutting down the server with `docker-compose down` and restarting it, I get a **XNAT System Path Verification Failure** error stating that `/data/xnat/archive` is missing. After further examination, all DICOMs in `/data/xnat/archive` are gone.

What would be the best practice to permanently store my archived data when using this container? Thanks for your help!

**Comment by vsoch** [comment]
hey @seantma ! I haven't tested robustly so this might not be ideal (and @johnflavin can chime in) but typically with Docker containers when you want data to persist from the container to the host, you need to map it with a [volume](https://docs.docker.com/engine/admin/volumes/volumes/). Basically, when the container is running, uploading data to an unmapped folder indeed does mean losing it when the container goes away. But if you map a volume to the host, the data will persist on the host (and then re-appear in the container given the same mapping.)

So for your example command, if you start running a single container you probably would want something like.

```
docker run $NAME -v /path/on/host:/data/xnat
```
but we are using docker-compose, so we probably want to add it as a volume to the compose file (and note this likely isn't done by default because it could be the case the user doesn't want it)

```
       volumes:
         - ./data:/data/xnat
         - ./webapps:/opt/tomcat/webapps
         - ./plugins:/data/xnat/home/plugins
         - /var/run/docker.sock:/var/run/docker.sock
```
See the top row - that would map a folder called "data" in the `$PWD` of the application on your host to `/data/xnat` in the container. If you want to save the entirety of data on the host you can move up one and just map `/data`. You can also change that path to be something more rooty on the host, like the equivalent `/data/xnat`

See if any of those options fit the bill, and then @johnflavin can chime in too, and we can discuss if we want to change any defaults. @johnflavin I'm happy to submit a PR with some documentation about how to help data persist if that is the best solution.

**Comment by johnflavin** [comment]
I agree with everything @vsoch said. I think the original purpose of this project was to get an XNAT quickly up and running, but not necessarily for long-term production use. So it doesn't permanently store your archive by default. That being said, if that is what you want to do, it is very easy to modify the compose file, as @vsoch showed, to persist your archive on the host machine and mount it into the XNAT image.

**Comment by rherrick** [comment]
Archive folder is now preserved by mapping volume to **xnat-data/archive**.
