### ISSUE TITLE
dicom scp receiver on 8104 unreachable

### ISSUE THREAD

**Issue by weeleon** [NrgXnat/xnat-docker-compose#64]
Hi, I am referring to the basic docker installation (without gradle) consisting of the NGINX, XNAT and PostGre. Within the Xnat docker I see that the Dicom SCP Receiver on port 8104 is on by default, but there seems no way of reaching this using the dicom export service of an application like Clinical Trial Processor.
Is it the case that nginx does not permit any traffic on 8104? I have tried to ping on this port and tried to push dicom images to the XNAT SCP Receiver without success.
Would you be able to provide a version where the XNAT SCP Receiver can be reached, or please guide me how to make this possible? Thank you in advance.

**Comment by rherrick** [comment]
It's not nginx that's not permitting traffic on port 8104, it's Docker. nginx [doesn't support non-http proxying in the standard configuration of its open-source version](https://docs.nginx.com/nginx/admin-guide/load-balancer/tcp-udp-load-balancer), but it doesn't really need to do so: instead you can just open whatever ports you have configured for DICOM receivers. The default is 8104, but you can add others as well.

To publish one or more DICOM receiver ports, add the following to your docker-compose.yml file:

```
services:
  xnat-web:
    ports:
      - 8104:8104
```

A couple of ports are already mapped for the branch of this project that uses Gradle, so you can look at that for a reference.

I think 8104 wasn't published by default here is because you _can_ add multiple mappings to other ports, but 8104 should probably be published out of the box.
