### ISSUE TITLE
RT-Struct display in viewer.

### ISSUE THREAD

**Issue by ramonemiliani93** [NrgXnat/xnat-docker-compose#87]
**Is your feature request related to a problem? Please describe.**

Hi, I have an RT Struct file associated to a DICOM series. I had no problems uploading both to XNAT (using the `features/dependency-mgmt` branch). I was expecting to be able to see the contours on the OHIF viewer but it doesn't seem to be supported. What would be the way to:

1. Display RT Struct files associated to the series on the OHIF viewer. 
2. Turn the RT Struct annotations into compatible structures (with the implemented contours/masks pane) to be edited and exported afterwards to train a machine learning model.

**Comment by JamesDarcy616** [comment]
The OHIF viewer supports RT Structs but it requires them to be uploaded as an ROI collection using the viewer's REST interface. Uploading the RT Structs as a generic DICOM series is not supported. The REST interface can be found on the Swagger page in the **ohif-roi-api** section. Upload can be done with any suitable REST client like curl, using your own code e.g. in Python or the [ROI Upload Assistant](https://bitbucket.org/icrimaginginformatics/roiuploadassistant/src/master/).

The RT Structs can be downloaded either via the XNAT UI or via the viewer's REST interface.

**Comment by ramonemiliani93** [comment]
Hey @JamesDarcy616, thanks a lot for the reply 🙌 I noticed you are the author of the `ROI Upload Assistant`, thanks for the work! I tried adding the compiled `RoiUploadAssistant-Fat.jar` of the project on the downloads tab to the `xnat-data/plugins` folder and restarted the Docker Compose setup but the XNAT application fails to start. Maybe I am misunderstanding how the setup is supposed to work or is there incompatibility between the current version the branch uses `XNAT 1.8.2` and the one you targeted the upload assistant for. If it is a compatibility issue, what would be the process for regenerating the package file? Otherwise, I would appreciate if you could point me to some resources on the intended setup.

The other approach you mentioned, uploading the ROI collection through the REST interface, do you refer to the REST XAPI section [here](https://bitbucket.org/icrimaginginformatics/ohif-viewer-xnat-plugin/src/master/#rest-xapi)? What would be the way to upload the contours using this approach.

Sorry if questions don't make much sense! I feel a bit lost 😓

**Comment by rherrick** [comment]
@ramonemiliani93 I'd guess XNAT is failing to start with `RoiUploadAssistant-Fat.jar` installed in the plugin folder because it's actually not an XNAT plugin, but does contain many external libraries that XNAT also references (a "fat" jar is a jar that includes the classes for a particular application _and also_ includes classes for all of that application's dependencies so that it can run as a stand-alone application from a single jar file). That could cause conflicts if the versions are different, e.g. XNAT calls `Foo.someMethod()` but the version of the `Foo` class included with the ROI upload assistant doesn't have that method...

Generally we can't debug issues with XNAT start-up or functioning without information from the XNAT logs. You can find the XNAT logs in `xnat-data/logs` (or something like that, maybe `xnat-data/home/logs`, it's been a little bit since I've worked with that configuration). That said, in this case, they're not important simply because I know that the issue is that that's not a plugin! Instead you should just run the ROI upload assistant directly:

```bash
 java -jar RoiUploadAssistant-Fat.jar
```
